language: objective-c

before_install:
  - wget https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - sudo pip install nose
  - brew update
  - brew rm boost
  - brew install webp icu4c boost postgis boost-python proj jpeg libtiff harfbuzz

install:
  - true

before_script:
  - true

script:
 - ./configure CXX="${CXX}" CC="${CC}"
 - make
 - make test
